/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti

import com.tuti.api.TutiApiClient
import com.tuti.api.authentication.SignInResponse
import com.tuti.model.SignInRequest

object Library {
    var jwt: String? = null

    @JvmStatic
    fun main(args: Array<String>) {
        val client = TutiApiClient()
        val tutiUsername = System.getenv("tuti_username") ?: error("missing env var: tuti_username")
        val tutiPassword = System.getenv("tuti_password") ?: error("missing env var: tuti_password")
        client.SignIn(SignInRequest(
            mobile = tutiUsername,
            password = tutiPassword
        ),
            onResponse = { signInResponse: SignInResponse ->
                val token = signInResponse.authorizationJWT
                client.authToken = token
                client.cards.list(
                    onResponse = { cards ->
                        cards.forEach { println("${it.cardId}: ${it.maskedPan}") }
                    },
                    onError = { _, error -> error?.printStackTrace() },
                )
            },
            onError = { _, _ -> })
    }
}

